In [2]:
import torch
import numpy as np
array= np.arange(1.0 ,8.0)
tensor =torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [3]:
array.dtype

dtype('float64')

In [4]:
torch.arange(1.0,8.0).dtype

torch.float32

In [ ]:
#whe converting from numpy to torch , pytorch reflects default data type 

In [5]:
array =array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [9]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor ,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [10]:
tensor= tensor+1
tensor , numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#concept of reproducability

In [ ]:
import os
from PIL import Image
import torchvision.transforms as transforms

# Set the paths
input_dir = 'D:/project_cardomom/Cardamom_disease_dataset(Augmented)/train/Cardamom___LeafSpot'  # Update this to the correct directory
output_dir = 'D:/project_cardomom/output'

# Create the output directory if it doesn't exist
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Define the transformation
resize_transform = transforms.Resize((320, 320))

# Iterate over the images in the input directory
for category in os.listdir(input_dir):
    category_dir = os.path.join(input_dir, category)
    if not os.path.isdir(category_dir):
        continue  # Skip non-directory files

    for filename in os.listdir(category_dir):
        # Load the image
        image_path = os.path.join(category_dir, filename)
        image = Image.open(image_path)

        # Apply the transformation
        resized_image = resize_transform(image)

        # Save the resized image to the output directory
        output_path = os.path.join(output_dir, filename)
        resized_image.save(output_path)

        print(f"Resized and saved {filename} to {output_path}")
