In [31]:
import torch

x = torch.arange(1, 10).reshape(1, 1, 9)
x, x.shape

(tensor([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]]), torch.Size([1, 1, 9]))

In [32]:
x[0, 0, 0]

tensor(1)

In [33]:
x[0, :, :]

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [34]:
t = x.reshape(9, 1, 1)
t

tensor([[[1]],

        [[2]],

        [[3]],

        [[4]],

        [[5]],

        [[6]],

        [[7]],

        [[8]],

        [[9]]])

In [35]:
x[0, 0, :]

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
x[:, 0, :]

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [37]:
x[:, :, 2]

tensor([[3]])

In [38]:
z = torch.device("cuda")
print(z)

cuda


In [39]:
# Squees and Unsquees
# permute
# lets create tesor
import torch

m = torch.arange(1.0, 10.0)
m, m.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [40]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [41]:
z = x.view(1, 9)
z, z.shape
# cahnging z changes x (beacause a view of a tensor the same memory  as orginal )

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [42]:
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([[[5, 2, 3, 4, 5, 6, 7, 8, 9]]]))

In [43]:
# stacking
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[[[5, 2, 3, 4, 5, 6, 7, 8, 9]]],


        [[[5, 2, 3, 4, 5, 6, 7, 8, 9]]],


        [[[5, 2, 3, 4, 5, 6, 7, 8, 9]]],


        [[[5, 2, 3, 4, 5, 6, 7, 8, 9]]]])

In [44]:
x_stacked = torch.vstack((x, x))
x_stacked

tensor([[[5, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[5, 2, 3, 4, 5, 6, 7, 8, 9]]])

# squees and  un squeees 

In [45]:
x_reshaped.shape


torch.Size([1, 9])

In [46]:
x_sqeezed = x_reshaped.squeeze()

In [47]:
x_reshaped.squeeze().shape


torch.Size([9])

In [49]:
print(f"previous tensor:{x_reshaped}")
print(f"Shape of tensor:{x_reshaped.shape}")
print(f"x_reshaped:{x_sqeezed}")
print(f"x_reshaped shape:{x_sqeezed.shape}")


previous tensor:tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Shape of tensor:torch.Size([1, 9])
x_reshaped:tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
x_reshaped shape:torch.Size([9])


In [50]:
print(f"previous dimension :{x_sqeezed}")
print(f"old shape:{x_sqeezed.shape}")
x_unsquuez=x_sqeezed.unsqueeze(dim=0)
print(f"new tensor:{x_unsquuez}")
print(f"shape:{x_unsquuez.shape}")

previous dimension :tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
old shape:torch.Size([9])
new tensor:tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
shape:torch.Size([1, 9])


In [ ]:
# torch .permute 
# re arrange dimension

In [54]:
x_oringinal= torch.rand(size=(224,224,3))
#permute orginal tesor to rearrange the axis or dimension
x_permute=x_oringinal.permute(2,0,1) #chage order 0->1 ,1>2,2->0
x_permute.shape

torch.Size([3, 224, 224])

In [60]:
x_oringinal[0,0,0]=.875
x_oringinal[0,0,0],x_permute[0,0,0]

(tensor(0.8750), tensor(0.8750))

In [ ]:
#indexing in pytorch same as indexing from numpy

In [61]:
#create a tensor